Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: ${codeuri}
      MemorySize: 128
      Policies:
      - AWSLambdaRole
      - AmazonS3ReadOnlyAccess
Metadata:
  SamTransformTest: true
