Resources:
  TriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: index.handler
      InlineCode: |
        const {
                DynamoDBDocument
              } = require("@aws-sdk/lib-dynamodb"),
              {
                DynamoDB
              } = require("@aws-sdk/client-dynamodb");
        exports.handler = async (event) => {
          console.log(JSON.stringify(event));
          const docClient = DynamoDBDocument.from(new DynamoDB());
          const response = await docClient.put({ 
            TableName: process.env.TABLE_NAME, 
            Item: {
              Id: 'TestInput1234'
            }
          });
          return response;
        };
      Environment:
        Variables:
          TABLE_NAME: !Ref MyTable

  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: Id
        KeyType: HASH

  MyWriteConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: TriggerFunction
      Destination:
        Id: MyTable
      Permissions:
      - Write
Metadata:
  SamTransformTest: true
