Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  TriggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt MyRole.Arn
      Runtime: nodejs18.x
      Handler: index.handler
      Code:
        ZipFile: |
          const {
            DynamoDBDocument
          } = require("@aws-sdk/lib-dynamodb"),
          {
            DynamoDB
          } = require("@aws-sdk/client-dynamodb");
          exports.handler = async (event) => {
            console.log(JSON.stringify(event));
            const docClient = DynamoDBDocument.from(new DynamoDB());
            try {
              const response = await docClient.scan({ TableName: process.env.TABLE_NAME, });
              return response
            }
            catch (err) {
              throw new Error('Failed to scan DynamoDb Table')
            }
          };
      Environment:
        Variables:
          TABLE_NAME: !Ref MyTable

  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: Id
        KeyType: HASH

  MyReadConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: TriggerFunction
      Destination:
        Id: MyTable
      Permissions:
      - Read
Metadata:
  SamTransformTest: true
