Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ${codeuri}
      AutoPublishAlias: Live
      AutoPublishAliasAllProperties: true
      Description: foo
Metadata:
  SamTransformTest: true
