Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: ${codeuri}
      AutoPublishAlias: Live
Metadata:
  SamTransformTest: true
